//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoGallery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public string PhotoPath { get; set; }
        public decimal PhotoSize { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UserId { get; set; }
    }
}
